apiVersion: kubedb.com/v1alpha1
kind: MongoDB
metadata:
  name: mariadb-restore
  namespace: demo
spec:
  version: "3.4-v3"
  storageType: Durable
  storage:
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  terminationPolicy: WipeOut

---
apiVersion: stash.appscode.com/v1beta1
kind: RestoreSession
metadata:
  name: mariadb-restore-01
  namespace: demo
  labels:
    kubedb.com/kind: Postgres
spec:
  runtimeSettings:
    pod:
      serviceAccountName: mariadb-backup-restore
  task:
    name: mariadb-restore-task
  repository:
    name: hello-repo
  target:
    ref:
      apiVersion: appcatalog.appscode.com/v1alpha1
      kind: AppBinding
      name: mariadb-restore
  rules:
  - snapshots: [latest]
